# Generated by Django 4.2.3 on 2023-07-12 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(blank='True', verbose_name=datetime.datetime(2023, 7, 12, 14, 31, 51, 824374))),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
    ]
