# Generated by Django 4.2.3 on 2023-07-12 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fills',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2023, 7, 12, 14, 48, 3, 346060)),
        ),
    ]
