# Generated by Django 4.2.3 on 2023-07-12 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_alter_fills_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fills',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 12, 14, 49, 2, 832910)),
        ),
    ]
