# Generated by Django 4.2.4 on 2023-09-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipeName', models.CharField(max_length=50)),
                ('MadeBy', models.CharField(max_length=70)),
                ('MakingTime', models.CharField(max_length=20)),
            ],
        ),
    ]
